### ISSUE TITLE
Text is not visible in JLab dark mode due to background change

### ISSUE THREAD

**Issue by jl-wynen** [silx-kit/jupyterlab-h5web#12]
When using Jupyter Lab's dark mode, the text in the 'inspect' view is black and almost invisible:
![darkmode](https://user-images.githubusercontent.com/11393224/106881510-ec1c1100-66dd-11eb-98ec-919d25f12628.png)
Similarly for the matrix view:
![darkmode2](https://user-images.githubusercontent.com/11393224/106881697-24bbea80-66de-11eb-8377-e3003d2f5c14.png)

**Comment by loichuder** [comment]
Good catch !

I will add a quickfix that should prevent the background color from changing. 

On a more long term plan, we can add a dark theme to h5web that can be tied to JupyterLab's theme. Thoughts @axelboc ?

**Comment by axelboc** [comment]
You could implement a dark theme directly in the extension, it's a matter of changing the CSS colour variables:

```css
/* Assuming this class is somewhere on a parent element of the app, like `body` */
.darkMode {
  --primary: ...;
  --primary-bg: ...;
  ...
}
```
