### ISSUE TITLE
[Heatmap] Dark mode inverts colormap

### ISSUE THREAD

**Issue by loichuder** [silx-kit/jupyterlab-h5web#52]
**Settings > JupyterLab Theme > JupyterLab light**

**Comment by loichuder** [comment]
Already reported in #34 in fact

**Comment by axelboc** [comment]
Hmm, maybe the selector `body[data-jp-theme-light='false']` is outdated?

```css

body[data-jp-theme-light='false'] .h5web-root {
  filter: invert();

  /* Set shadows to lighter colors so they remain dark once inverted */
  --btn-shadow-color: #f5f5f5;
  --btn-shadow-dark-color: #fafafa;
  --btn-shadow-darker-color: #fff;
}

body[data-jp-theme-light='false'] .h5web-root .no-invert,
body[data-jp-theme-light='false'] .h5web-root .no-invert-canvas > canvas {
  filter: invert(); /* invert back to normal colors */
}
```
